// Generated by LiveScript 1.2.0
var Color, Brush, WireframeBrush, ColorSamplerBrush, Lenny, EraserBrush, CopyPasteBrush, SketchBrush, getBrush;
Color = net.brehaut.Color;
Brush = (function(){
  Brush.displayName = 'Brush';
  var prototype = Brush.prototype, constructor = Brush;
  function Brush(radius, color, canvas){
    this.type = "default";
    this.isTool = false;
    this.radius = radius;
    this.color = color;
    this.canvas = canvas;
  }
  prototype.actionStart = function(x, y){
    this.canvas.context.moveTo(x, y);
    this.canvas.context.strokeStyle = this.color.toCSS();
    this.canvas.context.beginPath();
    this.canvas.context.lineWidth = this.radius;
    this.canvas.context.lineJoin = this.canvas.context.lineCap = 'round';
  };
  prototype.actionEnd = function(){
    this.canvas.context.closePath();
  };
  prototype.actionMove = function(x, y){
    this.canvas.context.lineTo(x, y);
    this.canvas.context.stroke();
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, len$, p;
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      p = data[i$];
      this.canvas.context.lineTo(p[0], p[1]);
    }
    this.canvas.context.stroke();
  };
  prototype.doAction = function(data){
    var i$, len$, p;
    if (data.length !== 0) {
      this.actionStart(data[0][0], data[0][1]);
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        p = data[i$];
        this.canvas.context.lineTo(p[0], p[1]);
      }
      this.canvas.context.stroke();
      this.actionEnd();
    }
  };
  return Brush;
}());
WireframeBrush = (function(superclass){
  var prototype = extend$((import$(WireframeBrush, superclass).displayName = 'WireframeBrush', WireframeBrush), superclass).prototype, constructor = WireframeBrush;
  function WireframeBrush(radius, color, canvas){
    WireframeBrush.superclass.apply(this, arguments);
    this.type = "wireframe";
  }
  prototype.actionStart = function(x, y){
    this.canvas.context.moveTo(x, y);
    this.canvas.context.strokeStyle = this.color.toCSS();
    this.canvas.context.beginPath();
    this.canvas.context.lineWidth = this.radius;
  };
  prototype.actionEnd = function(){
    this.canvas.context.closePath();
  };
  prototype.actionMove = function(x, y){
    var numpoints;
    this.canvas.context.lineTo(x, y);
    numpoints = this.canvas.action.data.length;
    if (numpoints >= 4) {
      this.canvas.context.lineTo(this.canvas.action.data[numpoints - 4][0], this.canvas.action.data[numpoints - 4][1]);
    }
    this.canvas.context.stroke();
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, to$, i, nearpoint;
    for (i$ = 1, to$ = data.length; i$ < to$; ++i$) {
      i = i$;
      this.canvas.context.lineTo(data[i][0], data[i][1]);
      nearpoint = data[i - 5];
      if (nearpoint) {
        this.canvas.context.moveTo(nearpoint[0], nearpoint[1]);
        this.canvas.context.lineTo(data[i][0], data[i][1]);
      }
    }
    this.canvas.context.stroke();
  };
  prototype.doAction = function(data){
    var i$, to$, i, nearpoint;
    if (data.length !== 0) {
      this.actionStart(data[0][0], data[0][1]);
      for (i$ = 1, to$ = data.length; i$ < to$; ++i$) {
        i = i$;
        this.canvas.context.lineTo(data[i][0], data[i][1]);
        nearpoint = data[i - 5];
        if (nearpoint) {
          this.canvas.context.moveTo(nearpoint[0], nearpoint[1]);
          this.canvas.context.lineTo(data[i][0], data[i][1]);
        }
      }
      this.canvas.context.stroke();
      this.actionEnd();
    }
  };
  return WireframeBrush;
}(Brush));
ColorSamplerBrush = (function(superclass){
  var prototype = extend$((import$(ColorSamplerBrush, superclass).displayName = 'ColorSamplerBrush', ColorSamplerBrush), superclass).prototype, constructor = ColorSamplerBrush;
  function ColorSamplerBrush(radius, color, canvas){
    ColorSamplerBrush.superclass.apply(this, arguments);
    this.type = "sampler";
  }
  prototype.actionStart = function(x, y){
    var p, a, hex;
    p = this.canvas.context.getImageData(x, y, 1, 1).data;
    a = p[3] / 255.0;
    hex = "rgba(" + p[0] + "," + p[1] + "," + p[2] + "," + a + ")";
    this.canvas.doColorChange(Color(hex));
  };
  prototype.actionEnd = function(){
    return;
  };
  prototype.actionMove = function(x, y){
    this.actionStart(x, y);
  };
  prototype.actionMoveData = function(data){};
  prototype.doAction = function(data){
    return;
  };
  return ColorSamplerBrush;
}(Brush));
Lenny = (function(superclass){
  var prototype = extend$((import$(Lenny, superclass).displayName = 'Lenny', Lenny), superclass).prototype, constructor = Lenny;
  function Lenny(radius, color, canvas){
    Lenny.superclass.apply(this, arguments);
    this.type = "lenny";
  }
  prototype.actionStart = function(x, y){
    this.canvas.context.moveTo(x, y);
    this.canvas.context.fillStyle = this.color.toCSS();
    this.canvas.context.font = "bold " + this.radius + "px arial";
    this.canvas.context.fillText("( ͡° ͜ʖ ͡°)", x, y);
  };
  prototype.actionEnd = function(){
    return;
  };
  prototype.actionMove = function(x, y){
    this.canvas.context.fillText("( ͡° ͜ʖ ͡°)", x, y);
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, len$, p;
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      p = data[i$];
      this.canvas.context.fillText("( ͡° ͜ʖ ͡°)", p[0], p[1]);
    }
  };
  prototype.doAction = function(data){
    var i$, len$, p;
    if (data.length !== 0) {
      this.actionStart(data[0][0], data[0][1]);
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        p = data[i$];
        this.canvas.context.fillText("( ͡° ͜ʖ ͡°)", p[0], p[1]);
      }
    }
  };
  return Lenny;
}(Brush));
EraserBrush = (function(superclass){
  var prototype = extend$((import$(EraserBrush, superclass).displayName = 'EraserBrush', EraserBrush), superclass).prototype, constructor = EraserBrush;
  function EraserBrush(radius, color, canvas){
    EraserBrush.superclass.apply(this, arguments);
    this.type = "eraser";
  }
  prototype.actionStart = function(x, y){
    var corner_x, corner_y;
    corner_x = x - this.radius >= 0 ? x - this.radius : 0;
    corner_y = y - this.radius >= 0 ? y - this.radius : 0;
    this.canvas.context.clearRect(corner_x, corner_y, this.radius * 2, this.radius * 2);
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionEnd = function(){
    return;
  };
  prototype.actionMove = function(x, y){
    var corner_x, corner_y;
    corner_x = x - this.radius >= 0 ? x - this.radius : 0;
    corner_y = y - this.radius >= 0 ? y - this.radius : 0;
    this.canvas.context.clearRect(corner_x, corner_y, this.radius * 2, this.radius * 2);
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, len$, p, corner_x, corner_y;
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      p = data[i$];
      corner_x = p[0] - this.radius >= 0 ? p[0] - this.radius : 0;
      corner_y = p[1] - this.radius >= 0 ? p[1] - this.radius : 0;
      this.canvas.context.clearRect(corner_x, corner_y, this.radius * 2, this.radius * 2);
    }
  };
  prototype.doAction = function(data){
    var i$, len$, p, corner_x, corner_y;
    if (data.length !== 0) {
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        p = data[i$];
        corner_x = p[0] - this.radius >= 0 ? p[0] - this.radius : 0;
        corner_y = p[1] - this.radius >= 0 ? p[1] - this.radius : 0;
        this.canvas.context.clearRect(corner_x, corner_y, this.radius * 2, this.radius * 2);
      }
    }
  };
  return EraserBrush;
}(Brush));
CopyPasteBrush = (function(superclass){
  var prototype = extend$((import$(CopyPasteBrush, superclass).displayName = 'CopyPasteBrush', CopyPasteBrush), superclass).prototype, constructor = CopyPasteBrush;
  function CopyPasteBrush(radius, color, canvas){
    CopyPasteBrush.superclass.apply(this, arguments);
    this.type = "copypaste";
    this.imgData = void 8;
  }
  prototype.actionStart = function(x, y){
    var corner_x, corner_y;
    corner_x = x - this.radius >= 0 ? x - this.radius : 0;
    corner_y = y - this.radius >= 0 ? y - this.radius : 0;
    this.imgData = this.canvas.context.getImageData(corner_x, corner_y, this.radius * 2, this.radius * 2);
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionEnd = function(){
    return;
  };
  prototype.actionMove = function(x, y){
    var corner_x, corner_y;
    corner_x = x - this.radius >= 0 ? x - this.radius : 0;
    corner_y = y - this.radius >= 0 ? y - this.radius : 0;
    this.canvas.context.putImageData(this.imgData, corner_x, corner_y);
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, len$, p, corner_x, corner_y;
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      p = data[i$];
      corner_x = p[0] - this.radius >= 0 ? p[0] - this.radius : 0;
      corner_y = p[1] - this.radius >= 0 ? p[1] - this.radius : 0;
      this.canvas.context.putImageData(this.imgData, corner_x, corner_y);
    }
  };
  prototype.doAction = function(data){
    var corner_x, corner_y, i$, len$, p;
    if (data.length !== 0) {
      corner_x = data[0][0] - this.radius >= 0 ? data[0][0] - this.radius : 0;
      corner_y = data[0][1] - this.radius >= 0 ? data[0][1] - this.radius : 0;
      this.imgData = this.canvas.context.getImageData(corner_x, corner_y, this.radius * 2, this.radius * 2);
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        p = data[i$];
        corner_x = p[0] - this.radius >= 0 ? p[0] - this.radius : 0;
        corner_y = p[1] - this.radius >= 0 ? p[1] - this.radius : 0;
        this.canvas.context.putImageData(this.imgData, corner_x, corner_y);
      }
    }
  };
  return CopyPasteBrush;
}(Brush));
SketchBrush = (function(superclass){
  var prototype = extend$((import$(SketchBrush, superclass).displayName = 'SketchBrush', SketchBrush), superclass).prototype, constructor = SketchBrush;
  function SketchBrush(radius, color, canvas){
    SketchBrush.superclass.apply(this, arguments);
    this.type = "sketch";
  }
  prototype.actionStart = function(x, y){
    this.canvas.context.moveTo(x, y);
    this.canvas.context.strokeStyle = this.color.toCSS();
    this.canvas.context.beginPath();
    this.canvas.context.lineWidth = this.radius;
    this.canvas.context.lineCap = 'round';
  };
  prototype.actionEnd = function(){
    this.canvas.context.closePath();
  };
  prototype.actionMove = function(x, y){
    var numpoints, lastpoint, i$, ref$, len$, p, dx, dy, d;
    numpoints = this.canvas.action.data.length;
    if (numpoints > 1) {
      lastpoint = this.canvas.action.data[numpoints - 1];
      this.canvas.context.moveTo(lastpoint[0], lastpoint[1]);
      this.canvas.context.lineTo(x, y);
      this.canvas.context.stroke();
      this.canvas.context.closePath();
      this.canvas.context.strokeStyle = this.color.setAlpha(this.color.getAlpha() / 0.3).toCSS();
      for (i$ = 0, len$ = (ref$ = this.canvas.action.data).length; i$ < len$; ++i$) {
        p = ref$[i$];
        dx = p[0] - x;
        dy = p[1] - y;
        d = dx * dx + dy * dy;
        if (d < 1000 && !(p[0] === lastpoint[0] && p[1] === lastpoint[1])) {
          this.canvas.context.beginPath();
          this.canvas.context.moveTo(x + dx * 0.2, y + dy * 0.2);
          this.canvas.context.lineTo(p[0] - dx * 0.2, p[1] - dy * 0.2);
        }
        this.canvas.context.stroke();
        this.canvas.context.closePath();
      }
      this.canvas.context.beginPath();
      this.canvas.context.strokeStyle = this.color.toCSS();
    }
    this.canvas.action.data.push([x, y]);
  };
  prototype.actionMoveData = function(data){
    var i$, len$, p, to$, i, j$, dx, dy, d;
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      p = data[i$];
      this.canvas.context.lineTo(p[0], p[1]);
    }
    this.canvas.context.stroke();
    this.canvas.context.closePath();
    this.canvas.context.strokeStyle = this.color.setAlpha(this.color.getAlpha() / 0.3).toCSS();
    for (i$ = 1, to$ = data.length; i$ < to$; ++i$) {
      i = i$;
      for (j$ = 0, len$ = data.length; j$ < len$; ++j$) {
        p = data[j$];
        dx = p[0] - data[i][0];
        dy = p[1] - data[i][1];
        d = dx * dx + dy * dy;
        if (d < 1000 && !(p[0] === data[i - 1][0] && p[1] === data[i - 1][1])) {
          this.canvas.context.beginPath();
          this.canvas.context.moveTo(data[i][0] + dx * 0.2, data[i][1] + dy * 0.2);
          this.canvas.context.lineTo(p[0] - dx * 0.2, p[1] - dy * 0.2);
        }
      }
      this.canvas.context.stroke();
      this.canvas.context.closePath();
    }
    this.canvas.context.beginPath();
    this.canvas.context.strokeStyle = this.color.toCSS();
  };
  prototype.doAction = function(data){
    var i$, len$, p, to$, i, j$, dx, dy, d;
    if (data.length !== 0) {
      this.actionStart(data[0][0], data[0][1]);
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        p = data[i$];
        this.canvas.context.lineTo(p[0], p[1]);
      }
      this.canvas.context.stroke();
      this.canvas.context.closePath();
      this.canvas.context.strokeStyle = this.color.setAlpha(this.color.getAlpha() / 0.3).toCSS();
      for (i$ = 1, to$ = data.length; i$ < to$; ++i$) {
        i = i$;
        for (j$ = 0, len$ = data.length; j$ < len$; ++j$) {
          p = data[j$];
          dx = p[0] - data[i][0];
          dy = p[1] - data[i][1];
          d = dx * dx + dy * dy;
          if (d < 1000 && !(p[0] === data[i - 1][0] && p[1] === data[i - 1][1])) {
            this.canvas.context.beginPath();
            this.canvas.context.moveTo(data[i][0] + dx * 0.2, data[i][1] + dy * 0.2);
            this.canvas.context.lineTo(p[0] - dx * 0.2, p[1] - dy * 0.2);
            this.canvas.context.stroke();
            this.canvas.context.closePath();
          }
        }
      }
    }
  };
  return SketchBrush;
}(Brush));
getBrush = function(brushtype, radius, color, canvas){
  switch (false) {
  case brushtype !== 'default':
    return new Brush(radius, color, canvas);
  case brushtype !== 'wireframe':
    return new WireframeBrush(radius, color, canvas);
  case brushtype !== 'sampler':
    return new ColorSamplerBrush(radius, color, canvas);
  case brushtype !== 'lenny':
    return new Lenny(radius, color, canvas);
  case brushtype !== 'eraser':
    return new EraserBrush(radius, color, canvas);
  case brushtype !== 'copypaste':
    return new CopyPasteBrush(radius, color, canvas);
  case brushtype !== 'sketch':
    return new SketchBrush(radius, color, canvas);
  }
};
function extend$(sub, sup){
  function fun(){} fun.prototype = (sub.superclass = sup).prototype;
  (sub.prototype = new fun).constructor = sub;
  if (typeof sup.extended == 'function') sup.extended(sub);
  return sub;
}
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}