// Generated by LiveScript 1.2.0
(function(){
  $(document).ready(function(){
    return $(document).ready(function(){
      var a;
      $(menu + " > ul > li ul").each(function(index, e){
        var count, content;
        count = $(e).find("li").length;
        content = "<span class=\"cnt\">" + count + "</span>";
        return $(e).closest("li").children("a").append(content);
      });
      $(menu + " ul ul li:odd").addClass("odd");
      $(menu + " ul ul li:even").addClass("even");
      $(menu + " > ul > li > a").click(function(){
        var checkElement;
        $(menu + " li").removeClass("active");
        $(this).closest("li").addClass("active");
        checkElement = $(this).next();
        if (checkElement.is("ul") && checkElement.is(":visible")) {
          $(this).closest("li").removeClass("active");
          checkElement.slideUp("normal");
        }
        if (checkElement.is("ul") && !checkElement.is(":visible")) {
          $(menu + " ul ul:visible").slideUp("normal");
          checkElement.slideDown("normal");
        }
        if ($(this).closest("li").find("ul").children().length === 0) {
          return true;
        } else {
          return false;
        }
      });
      a = 0;
      $(".showhide").click(function(e){
        var a;
        if (a === 0) {
          $(menu + "").animate({
            left: "152px"
          }, "slow").show();
          $(aShow + "").fadeToggle(500);
          $(aHide + "").fadeToggle(500);
          return a = 1;
        } else {
          $(menu + "").animate({
            'left:': 'left:',
            "-150px": "-150px"
          }, 'slow').show();
          $(aShow + "").fadeToggle(500);
          $(aHide + "").fadeToggle(500);
          return a = 0;
        }
      });
      return $(canvas + "").mousedown(function(e){
        return $(drawhere + "").fadeOut(150);
      });
    });
  });
}).call(this);
