// Generated by LiveScript 1.2.0
(function(){
  (function(){
    var createCanvas, init, container;
    createCanvas = function(parent, width, height){
      var canvas;
      width == null && (width = 100);
      height == null && (height = 100);
      canvas = {};
      canvas.node = document.createElement('canvas');
      canvas.node.width = width;
      canvas.node.height = height;
      canvas.context = canvas.node.getContext('2d');
      parent.appendChild(canvas.node);
      return canvas;
    };
    init = function(container, width, height, fillColor){
      var history, commands, canvas, context;
      history = [];
      commands = [];
      canvas = createCanvas(container, width, height);
      context = canvas.context;
      context.fillCircle = function(x, y, radius, fillColor){
        this.fillStyle = fillColor;
        this.beginPath();
        this.moveTo(x, y);
        this.arc(x, y, radius, 0, Math.PI * 2, false);
        this.fill();
      };
      canvas.node.onmousemove = function(e){
        var x, y, radius, fillColor;
        if (!canvas.isDrawing) {
          return;
        }
        x = e.pageX - this.offsetLeft;
        y = e.pageY - this.offsetTop;
        radius = 5;
        fillColor = '#000000';
        context.fillCircle(x, y, radius, fillColor);
        commands.push([x, y, radius, fillColor]);
      };
      canvas.node.onmousedown = function(e){
        canvas.isDrawing = true;
      };
      canvas.node.onmouseup = function(e){
        var commands;
        canvas.isDrawing = false;
        history.push([commands]);
        commands = [];
      };
      window.onkeydown = function(e){
        if (e.ctrlKey) {
          canvas.ctrlActivated = true;
        }
      };
      window.onkeyup = function(e){
        if (e.ctrlKey) {
          canvas.ctrlActivated = false;
        }
        switch (e.keyCode) {
        case 90:
          if (canvas.ctrlActivated) {
            history.pop();
            canvas.redraw();
          }
        }
      };
      canvas.redraw = function(){
        var i$, to$, i, j$, to1$, j;
        context.clearRect(0, 0, canvas.width, canvas.height);
        for (i$ = 0, to$ = history.length; i$ <= to$; ++i$) {
          i = i$;
          for (j$ = 0, to1$ = history[i].length; j$ <= to1$; ++j$) {
            j = j$;
            context.fillCircle(history[i][j][0], history[i][j][1], history[i][j][2], history[i][j][3]);
          }
        }
      };
    };
    container = document.getElementById('canvas');
    return init(container, window.innerWidth - 17, window.innerHeight - 45, '#000000');
  })();
}).call(this);
